### PR TITLE
re-enabled confirm button after failed onConfirm call

### PR DESCRIPTION
**Pull request by corymintz**

### CODE REVIEW

**Comment by denniskuczynski** [comment]
The intention here was if onConfirm returns true, it is doing asynchronous work and the modal should not be hidden until the caller completes that work.  So it is up to the caller to re-enable the button if they want to retry.

**Comment by corymintz** [comment]
Got it. Should there be a helper function on the ConfirmationModel to re-enable the button or do you expect subclasses OnConfirm to do `e.currentTarget.disabled = false`?

**Comment by denniskuczynski** [comment]
I typically do something like:
```
onConfirm: function(e) {
    var xhr = myAsyncRequest();
    xhr.fail(function() {
        $(e.target).prop('disabled', false);
    });
```

**Comment by denniskuczynski** [comment]
I'll probably change this API in a future revision as the return false API is non-obvious.

**Pull request closed without merging**
